places=['India','Dubai','America','London','Paris']
print(places)    
print (sorted(places))
print(places)   
places.reverse()
print(places)
places.reverse()
places.sort()
print(places)
places.sort(reverse=True)   
print(places)
